# Install script for directory: C:/Development/op3d_active/osgearth-3.0.0/src/applications

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/OSGEARTH")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_viewer/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_toc/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_tfs/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_boundarygen/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_overlayviewer/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_version/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_atlas/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_conv/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_3pv/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_exportgroundcover/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_clamp/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_manip/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_cluster/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_elevation/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_features/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_featurefilter/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_geodetic_graticule/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_los/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_terrainprofile/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_map/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_annotation/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_tracks/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_transform/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_horizon/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_http/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_measure/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_controls/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_shadercomp/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_imageoverlay/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_city/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_graticule/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_featurequery/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_occlusionculling/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_sequencecontrol/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_minimap/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_mrt/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_shadergen/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_pick/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_wfs/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_datetime/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_ephemeris/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_computerangecallback/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_skyview/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_server/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_srstest/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_lights/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_noisegen/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_infinitescroll/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_video/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_splat/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_htm/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_scenegraphcallbacks/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_drawables/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_magnify/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_eci/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_windows/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_callouts/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_decal/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_geocode/cmake_install.cmake")
  include("C:/Development/op3d_active/osgearth-3.0.0/msvc/src/applications/osgearth_imgui/cmake_install.cmake")

endif()

