# Install script for directory: C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/OSGEARTH")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Development/op3d_active/osgearth-3.0.0/msvc/lib/Debug/osgEarthd.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Development/op3d_active/osgearth-3.0.0/msvc/lib/Release/osgEarth.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Development/op3d_active/osgearth-3.0.0/msvc/lib/MinSizeRel/osgEarths.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Development/op3d_active/osgearth-3.0.0/msvc/lib/RelWithDebInfo/osgEarthrd.lib")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Development/op3d_active/osgearth-3.0.0/msvc/lib/Debug/osgEarthd.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Development/op3d_active/osgearth-3.0.0/msvc/lib/Release/osgEarth.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Development/op3d_active/osgearth-3.0.0/msvc/lib/MinSizeRel/osgEarths.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Development/op3d_active/osgearth-3.0.0/msvc/lib/RelWithDebInfo/osgEarthrd.dll")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/osgEarth" TYPE FILE FILES
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ArcGISServer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ArcGISTilePackage"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Bing"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Bounds"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Cache"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/CacheEstimator"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/CacheBin"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/CachePolicy"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/CacheSeed"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Callouts"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/CameraUtils"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Capabilities"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/CesiumIon"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/CascadeDrapingDecorator"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Clamping"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ClampableNode"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ClampingTechnique"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Color"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ColorFilter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Common"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Composite"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Config"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Containers"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Cube"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/CullingUtils"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/DateTime"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/DateTimeRange"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/DecalLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/DepthOffset"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/DrapeableNode"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/DrapingCullSet"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/DrapingTechnique"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/DrawInstanced"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ECEF"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ElevationLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ElevationLOD"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ElevationPool"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ElevationRanges"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ElevationQuery"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/EllipsoidIntersector"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Endian"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Export"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Extension"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/FadeEffect"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/FileUtils"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/GDAL"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/GDALDEM"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/GeoCommon"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/GeoData"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Geoid"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/GeoMath"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/GeoTransform"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/GeometryClamper"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/GLSLChunker"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/GLUtils"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/HeightFieldUtils"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Horizon"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/HorizonClipPlane"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/HTTPClient"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ImageLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ImageMosaic"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ImageToHeightFieldConverter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ImageUtils"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/InstanceCloud"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/IntersectionPicker"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/IOTypes"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/JoinPointsLinesFilter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/JsonUtils"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/LandCover"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/LandCoverLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Layer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/LayerReference"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/LayerShader"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Lighting"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/LineDrawable"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/LineFunctor"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Locators"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/LocalTangentPlane"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Map"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/MapCallback"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/MapInfo"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/MapModelChange"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/MapNode"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/MapNodeObserver"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/MaskLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/MaskSource"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Memory"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/MemCache"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/MetaTile"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Metrics"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/MBTiles"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ModelLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ModelSource"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/NativeProgramAdapter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/NodeUtils"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Notify"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/optional"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ObjectIndex"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/OverlayDecorator"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/PagedNode"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/PatchLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/PhongLightingEffect"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Picker"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/PluginLoader"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/PointDrawable"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/PowerlineLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/PrimitiveIntersector"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Profile"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Progress"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Random"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Registry"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ResourceReleaser"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Revisioning"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/SceneGraphCallback"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ScreenSpaceLayout"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ScreenSpaceLayoutImpl"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ScreenSpaceLayoutDeclutter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ScreenSpaceLayoutCallout"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Shaders"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ShaderFactory"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ShaderGenerator"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ShaderLoader"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ShaderMerger"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ShaderUtils"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/SimplexNoise"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/SpatialReference"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/StateSetCache"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Status"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/StringUtils"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TDTiles"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TaskService"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Terrain"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TerrainEffect"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TerrainOptions"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TerrainEngineNode"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TerrainEngineRequirements"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TerrainResources"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TerrainTileModel"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TerrainTileModelFactory"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TerrainTileNode"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Tessellator"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Text"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ThreeDTilesLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TileKey"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TileLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TileHandler"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TileRasterizer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TiledFeatureModelGraph"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TiledFeatureModelLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TileSource"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TileSourceElevationLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TileSourceImageLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TileVisitor"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TileCache"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TimeControl"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TraversalData"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ThreadingUtils"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TMS"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Units"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/URI"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Utils"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Version"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/VerticalDatum"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/VideoLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Viewpoint"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/VirtualProgram"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/VisibleLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/WMS"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/XmlUtils"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/XYZ"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ActivityMonitorTool"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/AutoClipPlaneHandler"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/AutoScaleCallback"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/AtlasBuilder"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ClipSpace"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Common"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Controls"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ContourMap"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ClampCallback"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ClusterNode"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/DebugImageLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/EarthManipulator"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Ephemeris"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ExampleResources"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Export"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/FlatteningLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Formatter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/FractalElevationLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/GARSGraticule"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/GeodeticGraticule"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/GeodeticLabelingEngine"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/GraticuleLabelingEngine"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/HTM"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/LatLongFormatter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/LineOfSight"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/LinearLineOfSight"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/LogarithmicDepthBuffer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/MeasureTool"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/MGRSFormatter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/MGRSGraticule"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/MouseCoordsTool"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/RadialLineOfSight"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/RTTPicker"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Shaders"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Shadowing"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/SimpleOceanLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/SimplePager"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Sky"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/SkyView"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/StarData"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TerrainProfile"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TileIndex"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TileIndexBuilder"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TFSPackager"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TMSBackFiller"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TopologyGraph"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/UTMGraticule"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/UTMLabelingEngine"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ViewFitter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/AltitudeFilter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/BufferFilter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/BuildGeometryFilter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/BuildTextFilter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/CentroidFilter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Common"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ConvertTypeFilter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/CropFilter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ExtrudeGeometryFilter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Feature"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/FeatureCursor"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/FeatureDisplayLayout"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/FeatureElevationLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/FeatureImageLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/FeatureIndex"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/FeatureMaskLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/FeatureModelGraph"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/FeatureModelLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/FeatureModelSource"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/FeatureSource"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/FeatureSourceIndexNode"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Filter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/FilterContext"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/GeometryCompiler"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/GeometryUtils"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ImageToFeatureLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/InstanceCloud.cpp"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/MVT"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/OgrUtils"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/OGRFeatureSource"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/PolygonizeLines"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ResampleFilter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ScaleFilter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Session"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ScatterFilter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Script"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ScriptEngine"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ScriptFilter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Shaders"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/SubstituteModelFilter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TessellateOperator"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TextSymbolizer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TFS"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TransformFilter"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/WireLines"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/XYZFeatureSource"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/WFS"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/AGG.h"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/AltitudeSymbol"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/BBoxSymbol"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/BillboardResource"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/BillboardSymbol"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Common"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/CoverageSymbol"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/CssUtils"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Expression"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ExtrusionSymbol"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Fill"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Geometry"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/GeometryFactory"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/GEOS"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/GeometryRasterizer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/IconResource"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/IconSymbol"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/InstanceResource"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/InstanceSymbol"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/LineSymbol"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/MeshConsolidator"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/MeshFlattener"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/MeshSubdivider"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ModelResource"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ModelSymbol"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/PointSymbol"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/PolygonSymbol"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Query"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/RenderSymbol"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Resource"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ResourceCache"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ResourceLibrary"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Skins"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Stroke"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Style"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/StyleSelector"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/StyleSheet"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Symbol"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Tags"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TextSymbol"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/AnnotationSettings"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/AnnotationData"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/AnnotationLayer"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/AnnotationNode"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/AnnotationRegistry"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/AnnotationUtils"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/BboxDrawable"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/CircleNode"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Common"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Draggers"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/EllipseNode"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Export"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/FeatureNode"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/GeoPositionNode"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/GeoPositionNodeAutoScaler"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/LocalGeometryNode"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ImageOverlay"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ImageOverlayEditor"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/LabelNode"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/ModelNode"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/PlaceNode"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/RectangleNode"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/TrackNode"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/rtree.h"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/FileGDBFeatureSource"
    "C:/Development/op3d_active/osgearth-3.0.0/msvc/build_include/osgEarth/BuildConfig.h"
    "C:/Development/op3d_active/osgearth-3.0.0/msvc/src/osgEarth/vector_tile.pb.h"
    "C:/Development/op3d_active/osgearth-3.0.0/src/osgEarth/Geocoder"
    )
endif()

